version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: geo_postgis
    environment:
      POSTGRES_DB: geo_backend
      POSTGRES_USER: geo_user
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  

  web:
    build: .
    container_name: geo_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: geo_backend
      DB_USER: geo_user
      DB_PASSWORD: 123456
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data:
